version: '3'
services:
  gatsby:
    build: .
    ports:
      - "8000:8000"  # Gatsby 개발 서버
      - "9000:9000"  # Gatsby 서비스 포트
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/
    command: npm run develop -- -H 0.0.0.0 